### ISSUE TITLE
when closing dialog, children components events are not sent so server

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-dialog-flow#40] opened 2018-02-19 15:47 UTC
I have a dialog with a date-picker bound to a BeanValidationBinder.

I read a bean, open the dialog, and before closing, it I set the bean to null to reset the dirty bean.

But opening the second time, the field is marked as invalid. The cause is that date-picker runs validation in client-side when detaching, because the field is null, it sets the invalid flag, but the event is not seen in server-side, therefore the server does not know that date-picker is invalid and does not update the property, even though binder tries to set it to invalid. 

You can reproduce the problem by running the following code

```
public class Order {
  @NotNull private LocalDate date;
  public Order(LocalDate date) {
    this.date = date;
  }
  public LocalDate getDate() {
    return date;
  }
  public void setDate(LocalDate date) {
    this.date = date;
  }
}

public Test1View() {
  Dialog dlg = new Dialog();
  DatePicker dt = new DatePicker();
  BeanValidationBinder<Order> binder = new BeanValidationBinder<>(Order.class);

  binder.bind(dt, "date");

  Button bClose = new Button("Close", e -> {
    binder.readBean(null);
    dlg.close();
  });
  Button bOpen = new Button("Open", e -> {
    binder.readBean(new Order(LocalDate.now()));
    dlg.open();
  });

  dlg.add(dt, bClose);
  add(bOpen);
}

```
Note that using a `Div` instead of the `Dialog` you can attach and detach it, and server side gets notifications correctly

```
public Test2View() {
  Div container = new Div();
  
  DatePicker dt = new DatePicker();
  BeanValidationBinder<Order> binder = new BeanValidationBinder<>(Order.class);

  binder.bind(dt, "date");
  Button bOpen = new Button("Open", e -> {
    binder.readBean(new Order(LocalDate.now()));
    add(container);
  });
  Button bClose = new Button("Close", e -> {
    binder.readBean(null);
    remove(container);
  });

  container.add(dt, bClose);
  add(bOpen);
}
```

Attached a simple project with all set for reproducing the problem

[dialog.zip](https://github.com/vaadin/vaadin-dialog-flow/files/1737363/dialog.zip)

An here you have a screenshot to see the issue in action

![issue-dialog](https://user-images.githubusercontent.com/161853/36385923-61699e44-1594-11e8-944c-d50c6a57493f.gif)

**Comment by gilberto-torrezan** [comment] 2018-03-01 12:52
After https://github.com/vaadin/vaadin-dialog-flow/pull/38 , the virtualChildren mechanism in Flow is not used anymore for Dialog, making it behave as expected when it comes to `@Id` mappings and children events.

Closing this since it is not reproducible anymore. Please comment on it if you still encounter problems.

**Closed by gilberto-torrezan** 2018-03-01 12:52 UTC
Labels: app starter, bug, components
