### ISSUE TITLE
Dialog child template is not responsive

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-dialog-flow#42] opened 2018-02-21 11:53 UTC
If dialog has several child templates with vaadin-form-layout then one of this templates is not responsive:

https://github.com/alexberazouski/skeleton-starter-flow-spring/tree/bug/form-layout-inside-dialog

0. Make browser window wide enough (1000px)
1. Click button, open dialog
2. click checkbox and see that 2 same templates look different depending on the order they were added to the dialog

**Comment by alexberazouski** [comment] 2018-02-21 11:53
please add App Starter label

**Comment by denis-anisimov** [comment] 2018-02-26 12:30
Not a Flow bug.
Either dialog or form layout issue.
I've created the ticket : https://github.com/vaadin/vaadin-form-layout/issues/66

**Comment by web-padawan** [comment] 2020-02-14 11:03
Closing as duplicate of https://github.com/vaadin/vaadin-form-layout/issues/66 which is fixed.

**Closed by web-padawan** 2020-02-14 11:03 UTC
Labels: app starter, awaits another issue, bug
